### ISSUE TITLE
[24h] Create (Think over) content for tabs in Website

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/Marketing#19]

**Comment by YuliyaSilvan** [comment]
https://docs.google.com/document/d/12XVfDpHgAUGYWyrjOX-1SK8iOgyFw-iye_UT9tRO14k/edit?usp=sharing

**Comment by YuliyaSilvan** [comment]
https://docs.google.com/document/d/1e63HWMh9AIRBkqkFzvETmgQOrOr0qnLlDVPpd-JOsT8/edit?usp=sharing
