### ISSUE TITLE
[1h] Write USP and positioning

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/Marketing#2]

**Comment by YuliyaSilvan** [comment]
USP: Short break for your long life
Positioning: Platform with easy and accessible office workouts, powered by AI and professionals in the field of PT and rehabilitation.
Mission: To help desk-bound employees make a healthy habit of regular physical activity in their daily life as well as to deal with discomfort and avoid negative consequences of sedentary lifestyle.
