### ISSUE TITLE
[32h] Content development for LikedIn

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/Marketing#23]

**Comment by YuliyaSilvan** [comment]
https://docs.google.com/spreadsheets/d/1V_gEZ4uk1KENzaHiXsdc5kACbAr6eleUP39E3pZf5Qg/edit#gid=0

**Comment by YuliyaSilvan** [comment]
https://drive.google.com/drive/u/0/folders/1sMq8fXRaUPBFthx23a8TaeWrTlFUhHxK
