### ISSUE TITLE
[h] Think over References or Description of a photo for a logo

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/Marketing#26]

**Comment by YuliyaSilvan** [comment]
Логотип в две строчки health uapp. 

1 вариант: попробовать сделать слияние букв h и u
2 вариант: раздельно (больше склоняюсь к нему)

![Image](https://user-images.githubusercontent.com/108801422/183892469-33d490b3-c5e9-450d-bf12-969aecdf1140.jpg)

Идея: буквы h и u отражают человечков, которые поднимают руки вверх и вниз соответственно = физическая активность, которую мы предлагаем.
Цвет: основной цвет попробовать черный, дугу от буквы h и u выделяем нашим фиолетовым для обеих букв 
либо градиентом (чтобы верхняя h попадала на фиолетовый, а нижняя на голубой) ЛИБО делаем два разных цвета для букв. Как лучше будет смотреться.
Предпочтения по шрифту: буквы мягкие, полукруглые. Отдельно отрисовать U и дугу от h.



![Image](https://user-images.githubusercontent.com/108801422/183892658-242d8350-7b29-4546-8c1a-0b32e1404007.png)
![Image](https://user-images.githubusercontent.com/108801422/183892657-f4ee40d8-3a7a-4fc8-a413-d3341b024b32.png)
![Image](https://user-images.githubusercontent.com/108801422/183892656-d958552f-6124-4512-9876-d547d685fcb5.png)
![Image](https://user-images.githubusercontent.com/108801422/183892659-91aa7f9c-635f-477f-9a10-0ee5e06268ab.png)
![Image](https://user-images.githubusercontent.com/108801422/183892660-738a1856-dfbf-4f6e-a248-79a7db86d622.png)
