### ISSUE TITLE
[6h] Create the text for HR interviews

### ISSUE THREAD

**Issue by buyalskaya** [healthUapp/Marketing#4]

**Comment by YuliyaSilvan** [comment]
https://docs.google.com/forms/d/16KFEecB5RA2ZC_3xWis-mH_vcAp-0syAiXLYtSVQahE/edit?usp=sharing

**Comment by YuliyaSilvan** [comment]
https://docs.google.com/document/d/1-MKbbOY4iMaucuuLbXXi3NZjGwLf0bULjMbQn04DMyQ/edit?usp=sharing

**Comment by YuliyaSilvan** [comment]
https://drive.google.com/drive/folders/1ExPfLPio7GS0lawB8FCf69gbQi-MQhWd?usp=sharing
